/* ------------------------------------------------------------------------------
<auto-generated>
    This file was generated by Sitefinity CLI v1.1.0.4
</auto-generated>
------------------------------------------------------------------------------ */

using SitefinityWebApp.Mvc.Models;
using System.Web.Mvc;
using Telerik.Sitefinity.Mvc;
using Telerik.Sitefinity.Personalization;

namespace SitefinityWebApp.Mvc.Controllers
{
	[ControllerToolboxItem(Name = "TestimonialCarousel_MVC", Title = "Testimonial Carousel", SectionName = "Blue Text")]
	public class TestimonialCarouselController : Controller, IPersonalizable
	{
		// GET: TestimonialCarousel
		public ActionResult Index()
		{
			
			var model = new TestimonialCarouselModel();
			model.Title = this.Title;
			model.Description = this.Description;
			return View(model);
		}
		
        protected override void HandleUnknownAction(string actionName)
        {
            this.ActionInvoker.InvokeAction(this.ControllerContext, "Index");
        }

		public string Title { get; set; } = "Title Not available";
		public string Description { get; set; } = " Description not available"; 
	}
}